const D=window.PULSE_DATA||{};const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const TASKS='pulse-tasks-v2',AUTO='pulse-auto-v1',THEME='pulse-theme';const storageGet=k=>{try{return localStorage.getItem(k)}catch{return null}};const storageSet=(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}};const read=(k,f)=>{try{const v=JSON.parse(storageGet(k));if(Array.isArray(f))return Array.isArray(v)?v:f;return v??f}catch{return f}};const write=(k,v)=>storageSet(k,JSON.stringify(v));
function theme(v){const next=v==='light'?'light':'dark';document.documentElement.dataset.theme=next;storageSet(THEME,next);$$('[data-theme-toggle]').forEach(b=>{b.textContent=next==='light'?'☾':'☀';b.setAttribute('aria-label',next==='dark'?'Ativar modo claro':'Ativar modo escuro')})}
function shell(){const s=$('[data-shell]');if(!s)return;const fallback=s.innerHTML;s.innerHTML='<aside class="sidebar"><div class="brand">PU<b>L</b>SE</div><div class="workspace-switch">Alureal Workspace<br><small class="muted">Operações</small></div><div class="side-section">Trabalho</div><nav class="side-nav"><a href="index.html">Visão geral</a><a href="clientes.html">Clientes</a><a href="operacoes.html">Operações</a><a href="mensagens.html">Mensagens</a><a href="relatorios.html">Relatórios</a><a href="automacoes.html">Automações</a></nav><div class="side-section">Admin</div><nav class="side-nav"><a href="equipe.html">Equipe</a><a href="configuracoes.html">Configurações</a></nav><div class="side-footer"><div class="user"><span class="avatar">MC</span><div><strong>Marina Costa</strong><br><small class="muted">Admin</small></div></div></div></aside><main class="main" data-main></main><nav class="mobile-nav"><a href="index.html">⌂<span>Início</span></a><a href="clientes.html">◎<span>Clientes</span></a><a href="operacoes.html">✓<span>Tarefas</span></a><a href="mensagens.html">✉<span>Inbox</span></a></nav>'}
function initTheme(){const raw=storageGet(THEME);const stored=raw==='dark'||raw==='light'?raw:null;let system='dark';try{system=window.matchMedia?.('(prefers-color-scheme: light)').matches?'light':'dark'}catch{}theme(stored||system);$$('[data-theme-toggle]').forEach(b=>b.onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark'))}
function topbar(title,sub=''){return '<header class="topbar"><div><h1>'+title+'</h1><span class="muted">'+sub+'</span></div><div class="top-actions"><input class="search" placeholder="Buscar no workspace"><button class="icon-btn" data-theme-toggle aria-label="Ativar modo claro">☀</button><button class="icon-btn">🔔</button></div></header>'}
function tasks(){return read(TASKS,D.tasks||[])}function saveTasks(v){write(TASKS,v)}
function dashboard(){const m=$('[data-main]');if(!m)return;m.innerHTML=topbar('Visão geral','Terça-feira, 29 de setembro')+'<section class="metrics"><article class="metric"><span>Receita processada</span><strong>R$ 184,7 mil</strong><small>+12,8%</small></article><article class="metric"><span>Clientes ativos</span><strong>418</strong><small>+28 no período</small></article><article class="metric"><span>Tarefas no prazo</span><strong>94%</strong><small>+3,1 p.p.</small></article><article class="metric"><span>Tempo de resposta</span><strong>21 min</strong><small>-6 min</small></article></section><section class="grid"><article class="card"><div class="card-head"><h2>Fluxo operacional</h2><span class="muted">14 dias</span></div><div class="chart">'+[34,48,42,68,56,76,64,86,73,92,78,88].map(h=>'<i class="bar" style="height:'+h+'%"></i>').join('')+'</div></article><article class="card"><div class="card-head"><h2>Prioridades</h2><a href="operacoes.html">Ver todas →</a></div><div class="task-list">'+tasks().filter(t=>t.status!=='done').slice(0,4).map(taskMarkup).join('')+'</div></article></section><section class="card" style="margin-top:12px"><div class="card-head"><h2>Clientes em movimento</h2><a href="clientes.html">Abrir CRM →</a></div>'+clientTable(D.clients.slice(0,4))+'</section>'}
function taskMarkup(t){return '<article class="task"><div><strong>'+t.title+'</strong><small>'+t.project+' · '+t.due+'</small></div><span class="priority">'+t.priority+'</span></article>'}
function clientTable(list){return '<div class="table"><div class="row header"><span>Cliente</span><span>Estágio</span><span>Responsável</span><span>Valor</span><span>Saúde</span></div>'+list.map(c=>'<a class="row" href="cliente.html?id='+c.id+'"><strong>'+c.name+'</strong><span class="stage">'+c.stage+'</span><span>'+c.owner+'</span><span>R$ '+Math.round(c.value/1000)+'k</span><span><div class="health"><i style="width:'+c.health+'%"></i></div></span></a>').join('')+'</div>'}
function clientsPage(){const m=$('[data-main]');m.innerHTML=topbar('Clientes','CRM e relacionamento')+'<div class="page-head"><div><h1>Pipeline de clientes</h1><p>'+D.clients.length+' contas no workspace</p></div><button class="button primary">+ Novo cliente</button></div>'+clientTable(D.clients)}
function clientDetail(){const m=$('[data-main]'),id=new URLSearchParams(location.search).get('id')||D.clients[0].id,c=D.clients.find(x=>x.id===id)||D.clients[0];m.innerHTML=topbar(c.name,c.segment)+'<section class="client-hero"><div class="client-title"><span class="client-logo">'+c.name.slice(0,2).toUpperCase()+'</span><div><h2 style="margin:0">'+c.name+'</h2><span class="muted">'+c.stage+' · '+c.owner+' · '+c.last+'</span></div></div><div class="client-actions"><button class="button">Mensagem</button><button class="button">Criar tarefa</button><button class="button primary">Nova proposta</button></div></section><div class="detail-grid"><section class="card"><div class="card-head"><h2>Timeline</h2></div><div class="timeline"><article class="timeline-item"><span>Hoje · 09:14</span><strong>Cliente respondeu à proposta</strong><p class="muted">Solicitou apenas ajuste na ordem de implantação.</p></article><article class="timeline-item"><span>Ontem · 16:20</span><strong>Reunião de revisão</strong><p class="muted">Escopo comercial alinhado.</p></article><article class="timeline-item"><span>25/09</span><strong>Diagnóstico concluído</strong><p class="muted">Principais gargalos documentados.</p></article></div></section><aside class="card"><h2>Resumo</h2><p class="muted">Valor potencial</p><strong style="font-size:28px">R$ '+Math.round(c.value/1000)+' mil</strong><p class="muted">Saúde da conta</p><div class="health"><i style="width:'+c.health+'%"></i></div></aside></div>'}
function operations(){const m=$('[data-main]'),ts=tasks();m.innerHTML=topbar('Operações','Tarefas e execução')+'<div class="page-head"><div><h1>Quadro operacional</h1><p>Arraste conceitualmente o trabalho entre etapas.</p></div><button class="button primary" data-new-task>+ Nova tarefa</button></div><section class="pipeline">'+['todo','doing','done','blocked'].map(status=>'<div class="lane" data-lane="'+status+'"><div class="lane-head"><strong>'+({todo:'A fazer',doing:'Em andamento',done:'Concluído',blocked:'Bloqueado'}[status])+'</strong><span class="muted">'+ts.filter(t=>t.status===status).length+'</span></div>'+ts.filter(t=>t.status===status).map(t=>'<article class="ticket"><h3>'+t.title+'</h3><p>'+t.project+' · '+t.owner+' · '+t.due+'</p>'+(status!=='done'?'<button data-complete="'+t.id+'">Concluir →</button>':'')+'</article>').join('')+'</div>').join('')+'</section>';$$('[data-complete]').forEach(b=>b.onclick=()=>{const x=tasks(),t=x.find(t=>t.id===b.dataset.complete);t.status='done';saveTasks(x);operations()})}
function messages(){const m=$('[data-main]');m.innerHTML=topbar('Mensagens','Clientes e equipe')+'<div class="message-layout"><section class="message-list">'+D.messages.map((x,i)=>'<article class="message-item '+(i===0?'active':'')+'" data-msg="'+x.id+'"><strong>'+x.from+'</strong><div>'+x.subject+'</div><small class="muted">'+x.time+'</small></article>').join('')+'</section><article class="message-view" data-message-view></article></div>';const show=id=>{const x=D.messages.find(m=>m.id===id)||D.messages[0];$('[data-message-view]').innerHTML='<span class="muted">'+x.from+'</span><h2>'+x.subject+'</h2><p>'+x.body+'</p><button class="button primary">Responder</button><button class="button" style="margin-left:6px">Criar tarefa</button>'};show(D.messages[0].id);$$('[data-msg]').forEach(e=>e.onclick=()=>{$$('[data-msg]').forEach(x=>x.classList.remove('active'));e.classList.add('active');show(e.dataset.msg)})}
function reports(){const m=$('[data-main]');m.innerHTML=topbar('Relatórios','Indicadores e tendências')+'<section class="report-grid">'+[['Receita','R$ 184,7 mil',[30,38,45,50,62,70,88]],['Conversão','28,4%',[42,48,55,52,61,68,74]],['SLA','21 min',[80,72,65,60,54,48,42]],['Entrega no prazo','94%',[68,72,76,84,82,90,94]]].map(r=>'<article class="report"><span class="muted">'+r[0]+'</span><h2>'+r[1]+'</h2><div class="spark">'+r[2].map(h=>'<i style="height:'+h+'%"></i>').join('')+'</div></article>').join('')+'</section>'}
function automations(){const m=$('[data-main]'),saved=read(AUTO,D.automations);m.innerHTML=topbar('Automações','Regras de execução')+'<div class="page-head"><div><h1>Automatize o repetitivo</h1><p>Gatilho → ação → responsável.</p></div><button class="button primary">+ Nova automação</button></div><section class="automation-grid">'+saved.map(a=>'<article class="automation"><div class="automation-head"><div><strong>'+a.name+'</strong><p class="muted">'+a.trigger+'</p></div><button class="switch '+(a.enabled?'on':'')+'" data-auto="'+a.id+'"></button></div><p>'+a.action+'</p></article>').join('')+'</section>';$$('[data-auto]').forEach(b=>b.onclick=()=>{const a=saved.find(x=>x.id===b.dataset.auto);a.enabled=!a.enabled;write(AUTO,saved);automations()})}
function team(){const m=$('[data-main]');m.innerHTML=topbar('Equipe','Pessoas e disponibilidade')+'<section class="team-grid">'+D.team.map(t=>'<article class="member"><div class="member-head"><span class="member-avatar">'+t.initials+'</span><div style="flex:1"><strong>'+t.name+'</strong><div class="muted">'+t.role+'</div></div><span class="stage">'+t.status+'</span></div></article>').join('')+'</section>'}
function settings(){const m=$('[data-main]');m.innerHTML=topbar('Configurações','Workspace')+'<section class="settings">'+[['Resumo diário','Receber prioridades pela manhã',true],['Alertas de SLA','Avisar conversas atrasadas',true],['Relatório semanal','Consolidar indicadores',false],['Modo foco','Ocultar métricas não essenciais',false],['Notificações push','Receber alertas críticos',true],['Sincronizar calendário','Criar eventos automaticamente',false]].map((s,i)=>'<article class="setting"><label><span><strong>'+s[0]+'</strong><p class="muted">'+s[1]+'</p></span><button class="switch '+(s[2]?'on':'')+'" data-setting="'+i+'"></button></label></article>').join('')+'</section>';$$('[data-setting]').forEach(b=>b.onclick=()=>b.classList.toggle('on'))}
function renderRoute(){
  const p=location.pathname.split('/').pop()||'index.html';
  if(p==='index.html'||p==='')dashboard();
  else if(p==='clientes.html')clientsPage();
  else if(p==='cliente.html')clientDetail();
  else if(p==='operacoes.html')operations();
  else if(p==='mensagens.html')messages();
  else if(p==='relatorios.html')reports();
  else if(p==='automacoes.html')automations();
  else if(p==='equipe.html')team();
  else if(p==='configuracoes.html')settings();
}
const safeRun=(name,fn)=>{try{fn()}catch(error){console.error('[PULSE] '+name+' failed',error);const main=$('[data-main]');if(main&&!main.textContent.trim())main.innerHTML='<section class="card"><h1>PULSE</h1><p class="muted">Conteúdo disponível parcialmente. Use a navegação lateral para continuar.</p></section>'}};
function init(){safeRun('shell',shell);safeRun('theme',initTheme);safeRun('route',renderRoute)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();